easy_admin:
    site_name: 'CMT <img style="max-width: 50px;" src="../logo.svg" />'
    user:
        display_name: true
        display_avatar: false
    entities:
        User:
            class: App\Entity\User
            label: 'User'
            list:
                title: 'User listing'
    design:
        brand_color: '#6a1b9a'
        menu:
            -   entity: User
                icon: 'user'