security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_API
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            pattern: /admin(.*)
            provider: fos_userbundle
            form_login:
                login_path: /admin/login
                check_path: /admin/login
            logout:
                path: admin_logout
                target: /admin/login
            anonymous: true
        main:
            pattern: ^/api
            provider: fos_userbundle
            stateless: true
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ ROLE_SUPER_ADMIN ] }
        - { path: ^/, roles: [ ROLE_USER ] }
