version: '3.3'
services:
    nginx:
        image: nginx:latest
        ports:
          - 8080:80
        volumes:
          - ./:/srv/www/collections
          - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
          - php
        networks:
          network:
            ipv4_address: 172.20.0.3
    php:
        build:
            context: ./.docker/php7.3-fpm
        ports:
            - 9090:9000
        volumes:
            - ./:/srv/www/collections
            - ./.docker/php7.3-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        networks:
            network:
                ipv4_address: 172.20.0.2
    mysql:
        image: mysql:5.7
        ports:
          - 13306:3306
        volumes:
          - my_data_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_DBNAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        depends_on:
          - php
        networks:
          network:
            ipv4_address: 172.20.0.4

volumes:
  my_data_volume:

networks:
  network:
      driver: bridge
      ipam:
        config:
          - subnet: 172.20.0.0/16